apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website-prod
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website-prod
    spec:
      containers:
        - image: crownlabs/website:stable
          name: website

