---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: website
  namespace: website
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website
  name: website
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website
    spec:
      containers:
      - image: crownlabs/website
        name: website
        resources: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: frontend-auxiliary
  namespace: website
spec:
  rules:
  - host: crownsite.crown-labs.ipv6.polito.it
    http:
      paths:
      - backend:
          serviceName: website
          servicePort: 80
        path: /
  tls:
  - hosts:
    - crownsite.crown-labs.ipv6.polito.it
    secretName: website-cert
