name: Install
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Push CrownSite image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/website
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"
      if: github.ref == 'refs/heads/master'
    - name: Build and Push CrownSite image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/website-test
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"
      if: github.ref != 'refs/heads/master'
