name: Install
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
    - name: Build and Push CrownSite image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/website
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"
      if: github.ref == 'refs/heads/master'
    - name: Build and Push CrownSite image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/website-test
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ github.sha }}"
      if: github.ref != 'refs/heads/master'
    - name: createKubeConfig
      run:  echo ${{ secrets.KUBECONFIG }} | base64 -d > ${{ github.workspace }}/kubeconfig
    - name: Deploy Production Website
      run: |
        docker run --rm --name kubectl \
                -v ${{ github.workspace }}/kubeconfig:/.kube/config \
                -v ${{ github.workspace }}/deployment:/deployment \
                crownlabs/builder:1.18 \
                apply -k /deployment/inventory/prod
      if: github.ref == 'refs/heads/master'
    - name: Deploy Test Website
      run: |
        docker run --rm --name kubectl \
                -v ${{ github.workspace }}/kubeconfig:/.kube/config \
                -v ${{ github.workspace }}/deployment:/deployment \
                crownlabs/builder:1.18 \
                apply -k /deployment/inventory/test
      if: github.ref != 'refs/heads/master'
    - name: Deploy Production Website (DRY-RUN)
      run: |
        docker run --rm --name kubectl \
                -v ${{ github.workspace }}/kubeconfig:/.kube/config \
                -v ${{ github.workspace }}/deployment:/deployment \
                crownlabs/builder:1.18 \
                apply -k /deployment/inventory/prod \
                --dry-run=server
      if: github.ref != 'refs/heads/master'
    - name: Deploy Production Website - Rollout containers
      run: |
        docker run --rm --name kubectl \
                -v ${{ github.workspace }}/kubeconfig:/.kube/config \
                -v ${{ github.workspace }}/deployment:/deployment \
                crownlabs/builder:1.18 \
                rollout restart -n website deployment website
      if: github.ref == 'refs/heads/master'
    - name: Deploy Test Website - Rollout Containers
      run: |
        docker run --rm --name kubectl \
                -v ${{ github.workspace }}/kubeconfig:/.kube/config \
                -v ${{ github.workspace }}/deployment:/deployment \
                crownlabs/builder:1.18 \
                rollout restart -n website-test deployment website
      if: github.ref != 'refs/heads/master'
